/*
Alex McClellan
Dr. Suchan
CSC 2212
14 October 2020

Note: I get a column is ambiguous error whenever I try to bring in fields, even though it is spelled correctly.
*/

-- 9.
SELECT COUNT(INV_NUMBER) FROM INVOICE;

-- 10.
SELECT * FROM CUSTOMER WHERE CUS_BALANCE > 500;

-- 11.
SELECT CUS_CODE, INV_NUMBER, P_DESCRIPT, LINE_UNITS, LINE_PRICE FROM CUSTOMER, INVOICE, PRODUCT;
ORDER BY CUS_CODE, INV_NUMBER, P_DESCRIPT;

-- 12.
SELECT CUS_CODE, INV_NUMBER, P_DESCRIPT, LINE_UNITS, LINE_PRICE FROM CUSTOMER, INVOICE, PRODUCT; 
SELECT LINE_UNITS, LINE_PRICE INTO SUBTOTAL FROM PRODUCT WHERE LINE_UNITS * LINE_PRICE;
ORDER BY CUS_CODE, INV_NUMBER, P_DESCRIPT;

-- 13.
SELECT CUS_CODE, INV_NUMBER, P_DESCRIPT, LINE_UNITS LU, LINE_PRICE LP FROM CUSTOMER, INVOICE, PRODUCT;
SELECT LINE_UNITS LU, LINE_PRICE LP INTO SUBTOTAL FROM PRODUCT WHERE LU * LP;
SELECT SUBTOTAL ST, CUS_CODE CC INTO TOTAL FROM PRODUCT, CUSTOMER WHERE (CC = CC) + ST;
ORDER BY CUS_CODE;

-- 14.
SELECT CUS_CODE, INV_NUMBER, P_DESCRIPT, LINE_UNITS LU, LINE_PRICE LP FROM CUSTOMER, INVOICE, PRODUCT;
SELECT LINE_UNITS LU, LINE_PRICE LP INTO SUBTOTAL FROM PRODUCT WHERE LU * LP;
SELECT SUBTOTAL ST, CUS_CODE CC INTO TOTAL FROM PRODUCT, CUSTOMER WHERE (CC = CC) + ST;
SELECT CUS_CODE, SUBTOTAL, TOTAL FROM CUSTOMER;
ORDER BY CUS_CODE;

-- 15.
SELECT CUS_CODE, INV_NUMBER, P_DESCRIPT, LINE_UNITS LU, LINE_PRICE LP FROM CUSTOMER, INVOICE, PRODUCT;
SELECT LINE_UNITS LU, LINE_PRICE LP INTO SUBTOTAL FROM PRODUCT WHERE LU * LP;
SELECT SUBTOTAL ST, CUS_CODE CC INTO TOTAL FROM PRODUCT, CUSTOMER WHERE (CC = CC) + ST;
SELECT CUS_CODE, INV_NUMBER FROM CUSTOMER, INVOICE WHERE (INV_NUMBER AND SUBTOTAL = PURCHASE_TOTAL);
AVG (TOTAL) INTO AVERAGE_PURCHASE_AMT;
SELECT CUS_CODE, CUS_BALANCE, TOTAL, PURCHASE_TOTAL, AVERAGE_PURCHASE_AMT FROM CUSTOMER;
ORDER BY CUS_CODE;

-- 16.
SELECT CUS_CODE, INV_NUMBER, P_DESCRIPT, LINE_UNITS LU, LINE_PRICE LP FROM CUSTOMER, INVOICE, PRODUCT;
SELECT LINE_UNITS LU, LINE_PRICE LP INTO Invoice Total FROM PRODUCT WHERE LU * LP;
SELECT INV_NUMBER, Invoice Total FROM INVOICE;
ORDER BY INV_NUMBER;

-- 17.
SELECT CUS_CODE, INV_NUMBER, P_DESCRIPT, LINE_UNITS LU, LINE_PRICE LP FROM CUSTOMER, INVOICE, PRODUCT;
SELECT LINE_UNITS LU, LINE_PRICE LP INTO Invoice Total FROM PRODUCT WHERE LU * LP;
SELECT CUS_CODE, INV_NUMBER, Invoice Total FROM CUSTOMER, PRODUCT;
ORDER BY CUS_CODE, INV_NUMBER;

-- 18.
SELECT CUS_CODE, INV_NUMBER, P_DESCRIPT, LINE_UNITS LU, LINE_PRICE LP FROM CUSTOMER, INVOICE, PRODUCT;
SELECT LINE_UNITS LU, LINE_PRICE LP INTO SUBTOTAL FROM PRODUCT WHERE LU * LP;
SELECT SUBTOTAL ST, CUS_CODE CC INTO TOTAL FROM PRODUCT, CUSTOMER WHERE (CC = CC) + ST;
SELECT CUS_CODE, INV_NUMBER FROM CUSTOMER, INVOICE WHERE (INV_NUMBER WITH CUS_CODE = PURCHASE_TOTAL);
SELECT CUS_CODE, PURCHASE_TOTAL INTO CUSTOMER_PURCHASES FROM CUSTOMER WHERE PURCHASE_TOTAL AND CUS_CODE = CUSTOMER_PURCHASES;
SELECT CUS_CODE, PURCHASE_TOTAL, CUSTOMER_PURCHASES FROM CUSTOMER;
ORDER BY CUS_CODE;